#582: Use new XML merger with intellij configuration files
devonfw/ide-settings pull request #68
Opened 2024-11-06 15:10 UTC by KianRolf

fixes devonfw/IDEasy#582

Moves intellij config files from setup to update and configures them for the new xml merger

2024-11-08 09:29 UTC, KianRolf commented
I am still not sure when exactly the OVERRIDE strategy is required

2024-11-12 14:00 UTC, KianRolf commented
Still needs some adjustments

2024-11-13 15:00 UTC, KianRolf commented
Should now be ready to be merged.

However some files are using override as merge strategy. This works for now but is not ideal.
The override merge strategy is used as a workaround to https://github.com/devonfw/IDEasy/issues/498.
Also i have discovered that the merge:id="name()" only works when the program runs in intellij (this is why the test are still green) but not in the finished build.
![Screenshot 2024-11-13 155421](https://github.com/user-attachments/assets/0fd0ad60-856a-4b9c-b311-26359d3778d5)

As a possible workaround i replaced the merge:id"name()" with xpathexpressions wich seemed to be working. So when #498 is resolved and the override merge strategies get removed i would recommend to try and use xpathexpressions

2024-11-14 09:53 UTC, hohwille commented
https://stackoverflow.com/questions/65455908/graalvm-xml-issue

2024-11-15 00:00 UTC, hohwille requested changes
@KianRolf thanks for this PR. Quite tricky to add all this `merge` attributes and namespaces.
Thanks also for testing this with IDEasy and finding the problems in the XML merger. 👍 
I finally found the time to review - sorry for the long delay.
There are a lot of review comments I lefts.
Some of them are because of problems we already have before this PR so they are not your "fault" but I just noticed when I closely looked into them during the review.
Some problems would have been prevented by proper `git mv` usage so that should be a good learning for the future since git is fundamental for software development.
Please have a look and try to address the review comments.

2024-11-15 08:34 UTC, KianRolf commented on intellij/workspace/update/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
It works if the parent of MavenGeneralSettings gets the override merge:strategy

2024-11-19 08:12 UTC, hohwille commented on intellij/workspace/update/.intellij/config/options/windows/keymap.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Was removed.

2024-11-21 23:27 UTC, hohwille commented on intellij/workspace/update/.intellij/config/options/jdk.table.xml
> +    <jdk version="2" merge:id="@version">
Will close this conversation now since strategy is currently `override`.

2024-11-22 10:09 UTC, merged